enum MathCategory {
  basic,
  functions,
  trig,
  calculus,
  geometry,
  matrices,
  greek,
  operators,
  brackets,
  arrows,
  sets,
  templates,
  format,
  misc,
}

class MathSymbol {
  final String label;
  final String tex;
  final MathCategory category;
  final bool isBuilder;
  final List<String>? variations;

  const MathSymbol({
    required this.label,
    required this.tex,
    required this.category,
    this.isBuilder = false,
    this.variations,
  });
}

const List<MathSymbol> mathSymbols = [
  // --- BASIC CATEGORY ---
  MathSymbol(label: '0', tex: '0', category: MathCategory.basic),
  MathSymbol(label: '1', tex: '1', category: MathCategory.basic),
  MathSymbol(label: '2', tex: '2', category: MathCategory.basic),
  MathSymbol(label: '3', tex: '3', category: MathCategory.basic),
  MathSymbol(label: '4', tex: '4', category: MathCategory.basic),
  MathSymbol(label: '5', tex: '5', category: MathCategory.basic),
  MathSymbol(label: '6', tex: '6', category: MathCategory.basic),
  MathSymbol(label: '7', tex: '7', category: MathCategory.basic),
  MathSymbol(label: '8', tex: '8', category: MathCategory.basic),
  MathSymbol(label: '9', tex: '9', category: MathCategory.basic),
  MathSymbol(label: '.', tex: '.', category: MathCategory.basic),
  MathSymbol(label: ',', tex: ',', category: MathCategory.basic),
  MathSymbol(label: '+', tex: '+', category: MathCategory.basic),
  MathSymbol(label: '-', tex: '-', category: MathCategory.basic),
  MathSymbol(label: '×', tex: r'\times', category: MathCategory.basic),
  MathSymbol(label: '÷', tex: r'\div', category: MathCategory.basic),
  MathSymbol(label: '=', tex: '=', category: MathCategory.basic),
  MathSymbol(label: 'x', tex: 'x', category: MathCategory.basic),
  MathSymbol(label: 'y', tex: 'y', category: MathCategory.basic),
  MathSymbol(label: 'z', tex: 'z', category: MathCategory.basic),
  MathSymbol(label: 'n', tex: 'n', category: MathCategory.basic),
  MathSymbol(label: 'π', tex: r'\pi', category: MathCategory.basic),
  MathSymbol(label: 'e', tex: 'e', category: MathCategory.basic),
  MathSymbol(label: 'i', tex: 'i', category: MathCategory.basic),
  MathSymbol(label: '(', tex: '(', category: MathCategory.basic),
  MathSymbol(label: ')', tex: ')', category: MathCategory.basic),
  MathSymbol(label: 'Fraction', tex: r'\frac{}{}', category: MathCategory.basic, isBuilder: true),
  MathSymbol(label: 'xⁿ', tex: r'^{}', category: MathCategory.basic, isBuilder: true),
  MathSymbol(label: '√', tex: r'\sqrt{}', category: MathCategory.basic, isBuilder: true),

  // --- FUNCTIONS CATEGORY ---
  MathSymbol(label: 'log', tex: r'\log', category: MathCategory.functions),
  MathSymbol(label: 'logₐ', tex: r'\log_{}', category: MathCategory.functions, isBuilder: true),
  MathSymbol(label: 'ln', tex: r'\ln', category: MathCategory.functions),
  MathSymbol(label: 'exp', tex: r'e^{}', category: MathCategory.functions, isBuilder: true),
  MathSymbol(label: '√', tex: r'\sqrt{}', category: MathCategory.functions, isBuilder: true),
  MathSymbol(label: '∛', tex: r'\sqrt[3]{}', category: MathCategory.functions, isBuilder: true),
  MathSymbol(label: 'ⁿ√', tex: r'\sqrt[]{}', category: MathCategory.functions, isBuilder: true),
  MathSymbol(label: '|x|', tex: r'|{}|', category: MathCategory.functions, isBuilder: true),
  MathSymbol(label: 'f(x)', tex: 'f(x)', category: MathCategory.functions),
  MathSymbol(label: 'g(x)', tex: 'g(x)', category: MathCategory.functions),
  MathSymbol(label: 'x!', tex: '!', category: MathCategory.functions),
  MathSymbol(label: 'mod', tex: r'\bmod', category: MathCategory.functions),

  // --- TRIG CATEGORY ---
  MathSymbol(label: 'sin', tex: r'\sin', category: MathCategory.trig),
  MathSymbol(label: 'cos', tex: r'\cos', category: MathCategory.trig),
  MathSymbol(label: 'tan', tex: r'\tan', category: MathCategory.trig),
  MathSymbol(label: 'csc', tex: r'\csc', category: MathCategory.trig),
  MathSymbol(label: 'sec', tex: r'\sec', category: MathCategory.trig),
  MathSymbol(label: 'cot', tex: r'\cot', category: MathCategory.trig),
  MathSymbol(label: 'arcsin', tex: r'\arcsin', category: MathCategory.trig),
  MathSymbol(label: 'arccos', tex: r'\arccos', category: MathCategory.trig),
  MathSymbol(label: 'arctan', tex: r'\arctan', category: MathCategory.trig),
  MathSymbol(label: 'sinh', tex: r'\sinh', category: MathCategory.trig),
  MathSymbol(label: 'cosh', tex: r'\cosh', category: MathCategory.trig),
  MathSymbol(label: 'tanh', tex: r'\tanh', category: MathCategory.trig),
  MathSymbol(label: 'θ', tex: r'\theta', category: MathCategory.trig),
  MathSymbol(label: 'φ', tex: r'\phi', category: MathCategory.trig),
  MathSymbol(label: '°', tex: r'^{\circ}', category: MathCategory.trig),

  // --- CALCULUS CATEGORY ---
  MathSymbol(label: '∫', tex: r'\int', category: MathCategory.calculus),
  MathSymbol(label: '∫ab', tex: r'\int_{}^{}^{}', category: MathCategory.calculus, isBuilder: true),
  MathSymbol(label: '∬', tex: r'\iint', category: MathCategory.calculus),
  MathSymbol(label: '∭', tex: r'\iiint', category: MathCategory.calculus),
  MathSymbol(label: '∮', tex: r'\oint', category: MathCategory.calculus),
  MathSymbol(label: 'd/dx', tex: r'\frac{d}{dx}', category: MathCategory.calculus, isBuilder: true),
  MathSymbol(label: 'dy/dx', tex: r'\frac{dy}{dx}', category: MathCategory.calculus, isBuilder: true),
  MathSymbol(label: '∂', tex: r'\partial', category: MathCategory.calculus),
  MathSymbol(label: '∇', tex: r'\nabla', category: MathCategory.calculus),
  MathSymbol(label: 'lim', tex: r'\lim_{x \to \infty}', category: MathCategory.calculus, isBuilder: true),
  MathSymbol(label: '∑', tex: r'\sum', category: MathCategory.calculus),
  MathSymbol(label: '∑ab', tex: r'\sum_{}^{}^{}', category: MathCategory.calculus, isBuilder: true),
  MathSymbol(label: '∏', tex: r'\prod', category: MathCategory.calculus),
  MathSymbol(label: '∏ab', tex: r'\prod_{}^{}^{}', category: MathCategory.calculus, isBuilder: true),
  MathSymbol(label: '∞', tex: r'\infty', category: MathCategory.calculus),
  MathSymbol(label: '∆', tex: r'\Delta', category: MathCategory.calculus),

  // --- OPERATORS CATEGORY ---
  MathSymbol(label: '<', tex: '<', category: MathCategory.operators),
  MathSymbol(label: '>', tex: '>', category: MathCategory.operators),
  MathSymbol(label: '≤', tex: r'\leq', category: MathCategory.operators),
  MathSymbol(label: '≥', tex: r'\geq', category: MathCategory.operators),
  MathSymbol(label: '≠', tex: r'\neq', category: MathCategory.operators),
  MathSymbol(label: '≈', tex: r'\approx', category: MathCategory.operators),
  MathSymbol(label: '±', tex: r'\pm', category: MathCategory.operators),
  MathSymbol(label: '∓', tex: r'\mp', category: MathCategory.operators),
  MathSymbol(label: '∝', tex: r'\propto', category: MathCategory.operators),
  MathSymbol(label: '∧', tex: r'\wedge', category: MathCategory.operators),
  MathSymbol(label: '∨', tex: r'\vee', category: MathCategory.operators),
  MathSymbol(label: '¬', tex: r'\neg', category: MathCategory.operators),
  MathSymbol(label: '⇒', tex: r'\Rightarrow', category: MathCategory.operators),
  MathSymbol(label: '⇔', tex: r'\Leftrightarrow', category: MathCategory.operators),
  MathSymbol(label: '∀', tex: r'\forall', category: MathCategory.operators),
  MathSymbol(label: '∃', tex: r'\exists', category: MathCategory.operators),

  // --- GREEK CATEGORY ---
  MathSymbol(label: 'α', tex: r'\alpha', category: MathCategory.greek),
  MathSymbol(label: 'β', tex: r'\beta', category: MathCategory.greek),
  MathSymbol(label: 'γ', tex: r'\gamma', category: MathCategory.greek),
  MathSymbol(label: 'δ', tex: r'\delta', category: MathCategory.greek),
  MathSymbol(label: 'ε', tex: r'\epsilon', category: MathCategory.greek),
  MathSymbol(label: 'ζ', tex: r'\zeta', category: MathCategory.greek),
  MathSymbol(label: 'η', tex: r'\eta', category: MathCategory.greek),
  MathSymbol(label: 'θ', tex: r'\theta', category: MathCategory.greek),
  MathSymbol(label: 'λ', tex: r'\lambda', category: MathCategory.greek),
  MathSymbol(label: 'μ', tex: r'\mu', category: MathCategory.greek),
  MathSymbol(label: 'π', tex: r'\pi', category: MathCategory.greek),
  MathSymbol(label: 'ρ', tex: r'\rho', category: MathCategory.greek),
  MathSymbol(label: 'σ', tex: r'\sigma', category: MathCategory.greek),
  MathSymbol(label: 'τ', tex: r'\tau', category: MathCategory.greek),
  MathSymbol(label: 'φ', tex: r'\phi', category: MathCategory.greek),
  MathSymbol(label: 'ω', tex: r'\omega', category: MathCategory.greek),
  MathSymbol(label: 'Γ', tex: r'\Gamma', category: MathCategory.greek),
  MathSymbol(label: 'Δ', tex: r'\Delta', category: MathCategory.greek),
  MathSymbol(label: 'Θ', tex: r'\Theta', category: MathCategory.greek),
  MathSymbol(label: 'Λ', tex: r'\Lambda', category: MathCategory.greek),
  MathSymbol(label: 'Π', tex: r'\Pi', category: MathCategory.greek),
  MathSymbol(label: 'Σ', tex: r'\Sigma', category: MathCategory.greek),
  MathSymbol(label: 'Φ', tex: r'\Phi', category: MathCategory.greek),
  MathSymbol(label: 'Ω', tex: r'\Omega', category: MathCategory.greek),

  // --- SETS CATEGORY ---
  MathSymbol(label: '∈', tex: r'\in', category: MathCategory.sets),
  MathSymbol(label: '∉', tex: r'\notin', category: MathCategory.sets),
  MathSymbol(label: '⊂', tex: r'\subset', category: MathCategory.sets),
  MathSymbol(label: '⊆', tex: r'\subseteq', category: MathCategory.sets),
  MathSymbol(label: '∪', tex: r'\cup', category: MathCategory.sets),
  MathSymbol(label: '∩', tex: r'\cap', category: MathCategory.sets),
  MathSymbol(label: '∅', tex: r'\empty', category: MathCategory.sets),
  MathSymbol(label: 'ℕ', tex: r'\mathbb{N}', category: MathCategory.sets),
  MathSymbol(label: 'ℤ', tex: r'\mathbb{Z}', category: MathCategory.sets),
  MathSymbol(label: 'ℚ', tex: r'\mathbb{Q}', category: MathCategory.sets),
  MathSymbol(label: 'ℝ', tex: r'\mathbb{R}', category: MathCategory.sets),
  MathSymbol(label: 'ℂ', tex: r'\mathbb{C}', category: MathCategory.sets),

  // --- BRACKETS CATEGORY ---
  MathSymbol(label: '(', tex: '(', category: MathCategory.brackets),
  MathSymbol(label: ')', tex: ')', category: MathCategory.brackets),
  MathSymbol(label: '[', tex: '[', category: MathCategory.brackets),
  MathSymbol(label: ']', tex: ']', category: MathCategory.brackets),
  MathSymbol(label: '{', tex: r'\{', category: MathCategory.brackets),
  MathSymbol(label: '}', tex: r'\}', category: MathCategory.brackets),
  MathSymbol(label: '⟨', tex: r'\langle', category: MathCategory.brackets),
  MathSymbol(label: '⟩', tex: r'\rangle', category: MathCategory.brackets),
  MathSymbol(label: '⌊', tex: r'\lfloor', category: MathCategory.brackets),
  MathSymbol(label: '⌋', tex: r'\rfloor', category: MathCategory.brackets),
  MathSymbol(label: '⌈', tex: r'\lceil', category: MathCategory.brackets),
  MathSymbol(label: '⌉', tex: r'\rceil', category: MathCategory.brackets),

  // --- GEOMETRY CATEGORY ---
  MathSymbol(label: '△', tex: r'\triangle', category: MathCategory.geometry),
  MathSymbol(label: '∠', tex: r'\angle', category: MathCategory.geometry),
  MathSymbol(label: '⊥', tex: r'\perp', category: MathCategory.geometry),
  MathSymbol(label: '∥', tex: r'\parallel', category: MathCategory.geometry),
  MathSymbol(label: '≅', tex: r'\cong', category: MathCategory.geometry),
  MathSymbol(label: '∼', tex: r'\sim', category: MathCategory.geometry),
  MathSymbol(label: '○', tex: r'\bigcirc', category: MathCategory.geometry),
  MathSymbol(label: '□', tex: r'\square', category: MathCategory.geometry),
  MathSymbol(label: 'AB', tex: r'\overline{AB}', category: MathCategory.geometry, isBuilder: true),
  MathSymbol(label: '→', tex: r'\vec{v}', category: MathCategory.geometry, isBuilder: true),

  // --- ARROWS CATEGORY ---
  MathSymbol(label: '←', tex: r'\leftarrow', category: MathCategory.arrows),
  MathSymbol(label: '→', tex: r'\rightarrow', category: MathCategory.arrows),
  MathSymbol(label: '↑', tex: r'\uparrow', category: MathCategory.arrows),
  MathSymbol(label: '↓', tex: r'\downarrow', category: MathCategory.arrows),
  MathSymbol(label: '↔', tex: r'\leftrightarrow', category: MathCategory.arrows),
  MathSymbol(label: '⇒', tex: r'\Rightarrow', category: MathCategory.arrows),
  MathSymbol(label: '⇔', tex: r'\Leftrightarrow', category: MathCategory.arrows),

  // --- MATRICES CATEGORY ---
  MathSymbol(label: '[2x2]', tex: r'\begin{pmatrix}  & \\  & \end{pmatrix}', category: MathCategory.matrices, isBuilder: true),
  MathSymbol(label: '[3x3]', tex: r'\begin{pmatrix}  &  & \\  &  & \\  &  & \end{pmatrix}', category: MathCategory.matrices, isBuilder: true),
  MathSymbol(label: 'det', tex: r'\det', category: MathCategory.matrices),

  // --- TEMPLATES CATEGORY ---
  MathSymbol(label: 'Quad', tex: r'x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}', category: MathCategory.templates),
  MathSymbol(label: 'Pyth', tex: r'a^2 + b^2 = c^2', category: MathCategory.templates),
  MathSymbol(label: 'Circle', tex: r'(x-h)^2 + (y-k)^2 = r^2', category: MathCategory.templates),
  MathSymbol(label: 'Line', tex: r'y = mx + b', category: MathCategory.templates),

  // --- MISC CATEGORY ---
  MathSymbol(label: '∞', tex: r'\infty', category: MathCategory.misc),
  MathSymbol(label: '!', tex: '!', category: MathCategory.misc),
  MathSymbol(label: '?', tex: '?', category: MathCategory.misc),
  MathSymbol(label: '%', tex: r'\%', category: MathCategory.misc),
  MathSymbol(label: '...', tex: r'\dots', category: MathCategory.misc),
];
