import 'dart:typed_data';

import 'package:edusheet/features/printing/domain/print_document_source.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:pdf/pdf.dart';

void main() {
  test('fixed print source caches generated bytes across preview and print', () async {
    var loadCount = 0;
    final source = PrintDocumentSource.fixed(
      title: 'Algebra Test',
      load: () async {
        loadCount += 1;
        return Uint8List.fromList(<int>[1, 2, 3, 4]);
      },
    );

    final previewBytes = await source.build(PdfPageFormat.a4);
    final printBytes = await source.build(PdfPageFormat.letter);

    expect(previewBytes, <int>[1, 2, 3, 4]);
    expect(printBytes, <int>[1, 2, 3, 4]);
    expect(loadCount, 1);
    expect(source.dynamicLayout, isFalse);
    expect(source.pdfFileName, 'Algebra Test.pdf');
  });

  test('pdf file name is not duplicated when title already has extension', () {
    final source = PrintDocumentSource.fixed(
      title: 'worksheet.PDF',
      load: () async => Uint8List(0),
    );

    expect(source.pdfFileName, 'worksheet.PDF');
  });
}
