import '../models/math_symbol.dart';

const List<MathSymbol> basicMathSymbols = <MathSymbol>[
  MathSymbol(
    id: 'math.b6589fc6ab0d',
    priority: 10,
    label: '0',
    tex: '0',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.356a192b7913',
    priority: 10,
    label: '1',
    tex: '1',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.da4b9237bacc',
    priority: 10,
    label: '2',
    tex: '2',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.77de68daecd8',
    priority: 10,
    label: '3',
    tex: '3',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.1b6453892473',
    priority: 10,
    label: '4',
    tex: '4',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.ac3478d69a3c',
    priority: 10,
    label: '5',
    tex: '5',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.c1dfd96eea8c',
    priority: 10,
    label: '6',
    tex: '6',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.902ba3cda188',
    priority: 10,
    label: '7',
    tex: '7',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.fe5dbbcea5ce',
    priority: 10,
    label: '8',
    tex: '8',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.0ade7c2cf97f',
    priority: 10,
    label: '9',
    tex: '9',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.3a52ce780950',
    priority: 10,
    label: '.',
    tex: '.',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.5c10b5b2cd67',
    priority: 10,
    label: ',',
    tex: ',',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.a979ef10cc6f',
    priority: 10,
    label: '+',
    tex: '+',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.3bc15c8aae3e',
    priority: 10,
    label: '-',
    tex: '-',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.5d2892f79a84',
    priority: 10,
    label: '×',
    tex: r'\times',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.669a988bd59c',
    priority: 10,
    label: '÷',
    tex: r'\div',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.21606782c65e',
    priority: 10,
    label: '=',
    tex: '=',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.11f6ad8ec52a',
    priority: 10,
    label: 'x',
    tex: 'x',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.95cb0bfd2977',
    priority: 10,
    label: 'y',
    tex: 'y',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.395df8f7c51f',
    priority: 10,
    label: 'z',
    tex: 'z',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.86f7e437faa5',
    priority: 10,
    label: 'a',
    tex: 'a',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.e9d71f5ee7c9',
    priority: 10,
    label: 'b',
    tex: 'b',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.d1854cae891e',
    priority: 10,
    label: 'n',
    tex: 'n',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.6ac47b6d7372',
    priority: 10,
    label: 'π',
    tex: r'\pi',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.58e6b3a414a1',
    priority: 10,
    label: 'e',
    tex: 'e',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.042dc4512fa3',
    priority: 10,
    label: 'i',
    tex: 'i',
    category: MathCategory.basic,
  ),
  MathSymbol(
    id: 'math.28ed3a797da3',
    kind: MathEntryKind.structure,
    priority: 10,
    label: '()',
    tex: '(',
    category: MathCategory.basic,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.74c0e719d9b6',
    kind: MathEntryKind.structure,
    priority: 10,
    label: 'x²',
    tex: r'^{2}',
    category: MathCategory.basic,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.55c73ac6f427',
    kind: MathEntryKind.structure,
    priority: 10,
    label: 'x³',
    tex: r'^{3}',
    category: MathCategory.basic,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.c8a8f0df16a9',
    kind: MathEntryKind.structure,
    spokenLabel: 'power or exponent',
    aliases: <String>['power', 'exponent', 'superscript'],
    priority: 10,
    label: 'xⁿ',
    tex: r'^{}',
    inputBehavior: MathInputBehavior.powerMode,
    category: MathCategory.basic,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.7d034bbf66ea',
    kind: MathEntryKind.structure,
    spokenLabel: 'subscript',
    aliases: <String>['subscript', 'index'],
    priority: 10,
    label: 'xᵢ',
    tex: r'_{}',
    inputBehavior: MathInputBehavior.subscriptMode,
    category: MathCategory.basic,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.c77ded9b8209',
    kind: MathEntryKind.structure,
    priority: 10,
    label: '√',
    tex: r'\sqrt{}',
    category: MathCategory.basic,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.61442a48150b',
    kind: MathEntryKind.structure,
    priority: 10,
    label: 'a⁄b',
    tex: r'\frac{}{}',
    category: MathCategory.basic,
    isBuilder: true,
  ),
];
