import '../models/math_symbol.dart';

const List<MathSymbol> calculusMathSymbols = <MathSymbol>[
  MathSymbol(id: 'math.e06a3bfdbbc0', priority: 50, label: '∫', tex: r'\int', category: MathCategory.calculus),
  MathSymbol(
      id: 'math.04738a8964a1',
      kind: MathEntryKind.structure,
      priority: 50,
      label: '∫ₐᵇ',
      tex: r'\int_{}^{}',
      inputBehavior: MathInputBehavior.subscriptMode,
      modeBaseSource: r'\int',
      category: MathCategory.calculus,
      isBuilder: true,
    ),
  MathSymbol(id: 'math.f6b13b46592f', priority: 50, label: '∬', tex: r'\iint', category: MathCategory.calculus),
  MathSymbol(id: 'math.407aa7e01eb6', priority: 50, label: '∭', tex: r'\iiint', category: MathCategory.calculus),
  MathSymbol(id: 'math.2b9e5199b9d1', priority: 50, label: '∮', tex: r'\oint', category: MathCategory.calculus),
  MathSymbol(
      id: 'math.2dec154b8373',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'd/dx',
      tex: r'\frac{d}{dx}',
      category: MathCategory.calculus,
      isBuilder: true,
    ),
  MathSymbol(
      id: 'math.089c2f4aa77c',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'dy/dx',
      tex: r'\frac{dy}{dx}',
      category: MathCategory.calculus,
      isBuilder: true,
    ),
  MathSymbol(
      id: 'math.cdeda3069520',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'd²/dx²',
      tex: r'\frac{d^2}{dx^2}',
      category: MathCategory.calculus,
      isBuilder: true,
    ),
  MathSymbol(id: 'math.b99cc6ef7869', priority: 50, label: '∂', tex: r'\partial', category: MathCategory.calculus),
  MathSymbol(id: 'math.473d84510527', priority: 50, label: '∇', tex: r'\nabla', category: MathCategory.calculus),
  MathSymbol(
      id: 'math.b5f88d588b39',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'lim',
      tex: r'\lim_{x \to \infty}',
      category: MathCategory.calculus,
      isBuilder: true,
    ),
  MathSymbol(id: 'math.782cb89fbe74', priority: 50, label: 'Σ', tex: r'\sum', category: MathCategory.calculus),
  MathSymbol(
      id: 'math.b1b9e334adec',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'Σₙ',
      tex: r'\sum_{}^{}',
      inputBehavior: MathInputBehavior.subscriptMode,
      modeBaseSource: r'\sum',
      category: MathCategory.calculus,
      isBuilder: true,
    ),
  MathSymbol(id: 'math.938b78cb2b7d', priority: 50, label: 'Π', tex: r'\prod', category: MathCategory.calculus),
  MathSymbol(
      id: 'math.aca7116f95cb',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'Πₙ',
      tex: r'\prod_{}^{}',
      inputBehavior: MathInputBehavior.subscriptMode,
      modeBaseSource: r'\prod',
      category: MathCategory.calculus,
      isBuilder: true,
    ),
  MathSymbol(id: 'math.9b97f26fbeb1', priority: 50, label: '∞', tex: r'\infty', category: MathCategory.calculus),
  MathSymbol(id: 'math.763bcca756ef', priority: 50, label: '∆', tex: r'\Delta', category: MathCategory.calculus),
];
