import '../models/math_edit_command.dart';
import '../models/math_symbol.dart';

const List<MathSymbol> calculusMathSymbols = <MathSymbol>[
  MathSymbol(
    id: 'math.e06a3bfdbbc0',
    priority: 50,
    label: '∫',
    tex: r'\int',
    category: MathCategory.calculus,
  ),
  MathSymbol(
    id: 'math.04738a8964a1',
    kind: MathEntryKind.structure,
    priority: 50,
    label: '∫ₐᵇ',
    tex: r'\int_{}^{}',
    editorCommand: MathEditCommands.integralWithLimits,
    inputBehavior: MathInputBehavior.subscriptMode,
    modeBaseSource: r'\int',
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.f6b13b46592f',
    priority: 50,
    label: '∬',
    tex: r'\iint',
    category: MathCategory.calculus,
  ),
  MathSymbol(
    id: 'math.407aa7e01eb6',
    priority: 50,
    label: '∭',
    tex: r'\iiint',
    category: MathCategory.calculus,
  ),
  MathSymbol(
    id: 'math.2b9e5199b9d1',
    priority: 50,
    label: '∮',
    tex: r'\oint',
    category: MathCategory.calculus,
  ),
  MathSymbol(
    id: 'math.2dec154b8373',
    kind: MathEntryKind.structure,
    priority: 50,
    label: 'd/dx',
    tex: r'\frac{d}{dx}',
    editorCommand: MathEditCommands.derivativeDByDx,
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.089c2f4aa77c',
    kind: MathEntryKind.structure,
    priority: 50,
    label: 'dy/dx',
    tex: r'\frac{dy}{dx}',
    editorCommand: MathEditCommands.derivativeDyByDx,
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.cdeda3069520',
    kind: MathEntryKind.structure,
    priority: 50,
    label: 'd²/dx²',
    tex: r'\frac{d^2}{dx^2}',
    editorCommand: MathEditCommands.secondDerivative,
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.b99cc6ef7869',
    priority: 50,
    label: '∂',
    tex: r'\partial',
    category: MathCategory.calculus,
  ),
  MathSymbol(
    id: 'math.473d84510527',
    priority: 50,
    label: '∇',
    tex: r'\nabla',
    category: MathCategory.calculus,
  ),
  MathSymbol(
    id: 'math.b5f88d588b39',
    kind: MathEntryKind.structure,
    priority: 50,
    label: 'lim',
    tex: r'\lim_{x \to \infty}',
    editorCommand: MathEditCommands.limitToInfinity,
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.782cb89fbe74',
    priority: 50,
    label: 'Σ',
    tex: r'\sum',
    category: MathCategory.calculus,
  ),
  MathSymbol(
    id: 'math.b1b9e334adec',
    kind: MathEntryKind.structure,
    priority: 50,
    label: 'Σₙ',
    tex: r'\sum_{}^{}',
    editorCommand: MathEditCommands.sumWithLimits,
    inputBehavior: MathInputBehavior.subscriptMode,
    modeBaseSource: r'\sum',
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.938b78cb2b7d',
    priority: 50,
    label: 'Π',
    tex: r'\prod',
    category: MathCategory.calculus,
  ),
  MathSymbol(
    id: 'math.aca7116f95cb',
    kind: MathEntryKind.structure,
    priority: 50,
    label: 'Πₙ',
    tex: r'\prod_{}^{}',
    editorCommand: MathEditCommands.productWithLimits,
    inputBehavior: MathInputBehavior.subscriptMode,
    modeBaseSource: r'\prod',
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.f85cced13c97',
    kind: MathEntryKind.structure,
    spokenLabel: 'generic derivative',
    aliases: <String>[
      'differentiate expression',
      'derivative builder',
      'd by d',
    ],
    priority: 50,
    label: 'd( )/d( )',
    tex: r'\frac{d{}}{d{}}',
    editorCommand: MathEditCommands.genericDerivative,
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.21aea054f713',
    kind: MathEntryKind.structure,
    spokenLabel: 'limit with condition',
    aliases: <String>['limit condition', 'limit x approaches a', 'lim builder'],
    priority: 50,
    label: 'limₓ→a',
    tex: r'\lim_{}',
    editorCommand: MathEditCommands.genericLimit,
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.e2e5b44cd513',
    kind: MathEntryKind.structure,
    spokenLabel: 'evaluation bar with limits',
    aliases: <String>[
      'evaluate from to',
      'evaluation bar',
      'upper lower endpoint',
    ],
    priority: 50,
    label: '|ₐᵇ',
    tex: r'|_{}^{}',
    editorCommand: MathEditCommands.evaluationBar,
    category: MathCategory.calculus,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.9b97f26fbeb1',
    priority: 50,
    label: '∞',
    tex: r'\infty',
    category: MathCategory.calculus,
  ),
  MathSymbol(
    id: 'math.763bcca756ef',
    priority: 50,
    label: '∆',
    tex: r'\Delta',
    category: MathCategory.calculus,
  ),
];
