import '../models/math_edit_command.dart';
import '../models/math_symbol.dart';

const List<MathSymbol> functionsMathSymbols = <MathSymbol>[
  MathSymbol(
    id: 'math.61442a48150b',
    kind: MathEntryKind.structure,
    priority: 30,
    label: 'a⁄b',
    tex: r'\frac{}{}',
    editorCommand: MathEditCommands.fraction,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.eb946338365d',
    kind: MathEntryKind.structure,
    priority: 30,
    label: '½',
    tex: r'\frac{1}{2}',
    editorCommand: MathEditCommands.half,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.64c94d13eeb3',
    kind: MathEntryKind.structure,
    priority: 30,
    label: '⅓',
    tex: r'\frac{1}{3}',
    editorCommand: MathEditCommands.oneThird,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.14b21b617fcd',
    kind: MathEntryKind.structure,
    priority: 30,
    label: '⅔',
    tex: r'\frac{2}{3}',
    editorCommand: MathEditCommands.twoThirds,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.c77ded9b8209',
    kind: MathEntryKind.structure,
    priority: 30,
    label: '√x',
    tex: r'\sqrt{}',
    editorCommand: MathEditCommands.squareRoot,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.8469a95b678c',
    kind: MathEntryKind.structure,
    priority: 30,
    label: '∛x',
    tex: r'\sqrt[3]{}',
    editorCommand: MathEditCommands.cubeRoot,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.fda850e20ff4',
    kind: MathEntryKind.structure,
    priority: 30,
    label: 'ⁿ√x',
    tex: r'\sqrt[]{}',
    editorCommand: MathEditCommands.nthRoot,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.36cb6bfb7f23',
    kind: MathEntryKind.structure,
    priority: 30,
    label: '|x|',
    tex: r'|{}|',
    editorCommand: MathEditCommands.absoluteValue,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.c0c686d8b8ef',
    kind: MathEntryKind.structure,
    spokenLabel: 'norm',
    aliases: <String>['norm', 'double bars', 'magnitude bars'],
    priority: 30,
    label: '‖x‖',
    tex: r'||{}||',
    editorCommand: MathEditCommands.norm,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.74c0e719d9b6',
    kind: MathEntryKind.structure,
    priority: 30,
    label: 'x²',
    tex: r'^{2}',
    editorCommand: MathEditCommands.squared,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.55c73ac6f427',
    kind: MathEntryKind.structure,
    priority: 30,
    label: 'x³',
    tex: r'^{3}',
    editorCommand: MathEditCommands.cubed,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.c8a8f0df16a9',
    kind: MathEntryKind.structure,
    spokenLabel: 'power or exponent',
    aliases: <String>['power', 'exponent', 'superscript'],
    priority: 30,
    label: 'xⁿ',
    tex: r'^{}',
    editorCommand: MathEditCommands.superscriptSlot,
    inputBehavior: MathInputBehavior.powerMode,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.7d034bbf66ea',
    kind: MathEntryKind.structure,
    spokenLabel: 'subscript',
    aliases: <String>['subscript', 'index'],
    priority: 30,
    label: 'xᵢ',
    tex: r'_{}',
    editorCommand: MathEditCommands.subscriptSlot,
    inputBehavior: MathInputBehavior.subscriptMode,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.b9562e522b28',
    priority: 30,
    label: 'log',
    tex: r'\log',
    editorCommand: MathEditCommands.logCall,
    category: MathCategory.functions,
  ),
  MathSymbol(
    id: 'math.ba9e6b063c69',
    kind: MathEntryKind.structure,
    priority: 30,
    label: 'logₐ',
    tex: r'\log_{}',
    editorCommand: MathEditCommands.logWithBase,
    inputBehavior: MathInputBehavior.subscriptMode,
    modeBaseSource: r'\log',
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.32c31c1837a9',
    priority: 30,
    label: 'ln',
    tex: r'\ln',
    editorCommand: MathEditCommands.lnCall,
    category: MathCategory.functions,
  ),
  MathSymbol(
    id: 'math.643cc544234b',
    kind: MathEntryKind.structure,
    priority: 30,
    label: 'eˣ',
    tex: r'e^{}',
    editorCommand: MathEditCommands.exponential,
    inputBehavior: MathInputBehavior.powerMode,
    modeBaseSource: 'e',
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.3e03f4706048',
    priority: 30,
    label: 'f(x)',
    tex: 'f(x)',
    category: MathCategory.functions,
  ),
  MathSymbol(
    id: 'math.65405422ff71',
    priority: 30,
    label: 'g(x)',
    tex: 'g(x)',
    category: MathCategory.functions,
  ),
  MathSymbol(
    id: 'math.0ab8318acaf6',
    priority: 30,
    label: 'x!',
    tex: '!',
    category: MathCategory.functions,
  ),
  MathSymbol(
    id: 'math.f52a9a86d828',
    priority: 30,
    label: 'mod',
    tex: r'\bmod',
    category: MathCategory.functions,
  ),
  MathSymbol(
    id: 'math.c87330dfad00',
    kind: MathEntryKind.structure,
    spokenLabel: 'subscript and superscript',
    aliases: <String>['subscript superscript', 'index and power', 'x i n'],
    priority: 30,
    label: 'xᵢⁿ',
    tex: r'_{}^{}',
    editorCommand: MathEditCommands.subscriptAndSuperscript,
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.365365940bd1',
    kind: MathEntryKind.structure,
    spokenLabel: 'inner product',
    aliases: <String>['inner product', 'angle pair', 'dot product brackets'],
    priority: 30,
    label: '⟨a,b⟩',
    tex: r'\langle{},{}\rangle',
    editorCommand: MathEditCommands.innerProduct,
    category: MathCategory.functions,
    subjects: <MathSubject>[MathSubject.linearAlgebra],
    levels: <MathEducationLevel>[
      MathEducationLevel.higherSecondary,
      MathEducationLevel.university,
    ],
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.32e7f2a6e420',
    kind: MathEntryKind.structure,
    priority: 30,
    label: '1 a⁄b',
    tex: r'1\frac{}{}',
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.9a73107d34f1',
    kind: MathEntryKind.structure,
    priority: 30,
    label: 'a×10ⁿ',
    tex: r'{}\times 10^{}',
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.e5555c134cc0',
    kind: MathEntryKind.structure,
    priority: 30,
    label: '0.3̅',
    tex: r'0.\overline{3}',
    category: MathCategory.functions,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.2b6e79c84d23',
    kind: MathEntryKind.structure,
    priority: 30,
    label: 'cases',
    tex: r'f(x)=\begin{cases} & \\ & \end{cases}',
    category: MathCategory.functions,
    editorCommand: MathEditCommands.piecewise2Rows,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.00435dd55494',
    kind: MathEntryKind.structure,
    priority: 30,
    label: '2 equations',
    tex: r'\begin{cases} ax+by=c \\ dx+ey=f \end{cases}',
    category: MathCategory.functions,
    isBuilder: true,
  ),
];
