import '../models/math_symbol.dart';

const List<MathSymbol> geometryMathSymbols = <MathSymbol>[
  MathSymbol(id: 'math.a4fdf592fa30', priority: 50, label: '△', tex: r'\triangle', category: MathCategory.geometry),
  MathSymbol(id: 'math.d40589d68d41', priority: 50, label: '∠', tex: r'\angle', category: MathCategory.geometry),
  MathSymbol(id: 'math.67833d716365', priority: 50, label: '⊥', tex: r'\perp', category: MathCategory.geometry),
  MathSymbol(id: 'math.2e8b77536b7a', priority: 50, label: '∥', tex: r'\parallel', category: MathCategory.geometry),
  MathSymbol(id: 'math.fcf44bbe42dd', priority: 50, label: '≅', tex: r'\cong', category: MathCategory.geometry),
  MathSymbol(id: 'math.ec2243ccce89', priority: 50, label: '∼', tex: r'\sim', category: MathCategory.geometry),
  MathSymbol(id: 'math.bafd5e286b3e', priority: 50, label: '○', tex: r'\bigcirc', category: MathCategory.geometry),
  MathSymbol(id: 'math.7d166ea04691', priority: 50, label: '□', tex: r'\square', category: MathCategory.geometry),
  MathSymbol(
      id: 'math.39a3a59a8f52',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'v⃗',
      tex: r'\vec{v}',
      category: MathCategory.geometry,
      isBuilder: true,
    ),
  MathSymbol(
      id: 'math.6cebb2127a73',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'arc',
      tex: r'\overset{\frown}{AB}',
      category: MathCategory.geometry,
      isBuilder: true,
    ),
  MathSymbol(
      id: 'math.cbf7d8650cad',
      priority: 50,
      label: 'cm²',
      tex: r'\text{cm}^{2}',
      category: MathCategory.geometry,
    ),
  MathSymbol(
      id: 'math.a0afa9f8fada',
      priority: 50,
      label: 'cm³',
      tex: r'\text{cm}^{3}',
      category: MathCategory.geometry,
    ),
  MathSymbol(
      id: 'math.2936a38a3166',
      kind: MathEntryKind.structure,
      priority: 50,
      label: '∠ABC',
      tex: r'\angle ABC',
      category: MathCategory.geometry,
      isBuilder: true,
    ),
  MathSymbol(
      id: 'math.2d6406c114fd',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'm∠ABC',
      tex: r'm\angle ABC',
      category: MathCategory.geometry,
      isBuilder: true,
    ),
  MathSymbol(
      id: 'math.051212af7481',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'AB̅',
      tex: r'\overline{AB}',
      category: MathCategory.geometry,
      isBuilder: true,
    ),
  MathSymbol(
      id: 'math.9dac66328702',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'AB⃗',
      tex: r'\overrightarrow{AB}',
      category: MathCategory.geometry,
      isBuilder: true,
    ),
  MathSymbol(
      id: 'math.9b1cbcb39de0',
      kind: MathEntryKind.structure,
      priority: 50,
      label: 'AB↔',
      tex: r'\overleftrightarrow{AB}',
      category: MathCategory.geometry,
      isBuilder: true,
    ),
  MathSymbol(id: 'math.86654659b468', priority: 50, label: '∟', tex: '∟', category: MathCategory.geometry),
  MathSymbol(id: 'math.63c6b4deb4dd', priority: 50, label: '⌒AB', tex: r'\widehat{AB}', category: MathCategory.geometry),
  MathSymbol(id: 'math.29330ac23972', priority: 50, label: '△ABC', tex: r'\triangle ABC', category: MathCategory.geometry),
  MathSymbol(id: 'math.8e7cfd37f333', priority: 50, label: '▱', tex: '▱', category: MathCategory.geometry),
  MathSymbol(id: 'math.7bf6761efbf9', priority: 50, label: '⌀', tex: '⌀', category: MathCategory.geometry),
  MathSymbol(id: 'math.5be9c83dff6a', priority: 50, label: '°', tex: r'^{\circ}', category: MathCategory.geometry),
  MathSymbol(id: 'math.2376c7948934', priority: 50, label: '′', tex: r'^{\prime}', category: MathCategory.geometry),
  MathSymbol(id: 'math.1ab831b80d85', priority: 50, label: '″', tex: r'^{\prime\prime}', category: MathCategory.geometry),
  MathSymbol(id: 'math.8eb257c89937', priority: 50, label: 'mm', tex: r'\text{mm}', category: MathCategory.geometry),
  MathSymbol(id: 'math.d3166473db9f', priority: 50, label: 'cm', tex: r'\text{cm}', category: MathCategory.geometry),
  MathSymbol(id: 'math.ca5589d59ac1', priority: 50, label: 'm', tex: r'\text{m}', category: MathCategory.geometry),
  MathSymbol(id: 'math.e7d8e9edf2c1', priority: 50, label: 'km', tex: r'\text{km}', category: MathCategory.geometry),
];
