import '../models/math_symbol.dart';

const List<MathSymbol> physicsMathSymbols = <MathSymbol>[
  MathSymbol(
    id: 'math.763bcca756ef',
    priority: 60,
    label: 'Δ',
    tex: r'\Delta',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.fdecfb421643',
    priority: 60,
    label: 'Δt',
    tex: r'\Delta t',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.39a3a59a8f52',
    kind: MathEntryKind.structure,
    priority: 60,
    label: 'v⃗',
    tex: r'\vec{v}',
    category: MathCategory.physics,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.b0682d270b2b',
    kind: MathEntryKind.structure,
    priority: 60,
    label: 'F⃗',
    tex: r'\vec{F}',
    category: MathCategory.physics,
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.b3931f1ce298',
    priority: 60,
    label: 'λ',
    tex: r'\lambda',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.c77a25750c58',
    priority: 60,
    label: 'ρ',
    tex: r'\rho',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.73b077a63e22',
    priority: 60,
    label: 'ω',
    tex: r'\omega',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.3a4e56595df1',
    priority: 60,
    label: 'μ',
    tex: r'\mu',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.4959627bdb88',
    priority: 60,
    label: 'Ω',
    tex: r'\Omega',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.63adb29f9be3',
    priority: 60,
    label: '°C',
    tex: r'^{\circ}\text{C}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.796f0e9d8bac',
    priority: 60,
    label: 'm/s',
    tex: r'\text{m/s}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.8efffa414888',
    priority: 60,
    label: 'm/s²',
    tex: r'\text{m/s}^{2}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.00b8c3a0ecff',
    priority: 60,
    label: 'kg',
    tex: r'\text{kg}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.7eb5dae92cce',
    priority: 60,
    label: 'N',
    tex: r'\text{N}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.185a22775290',
    priority: 60,
    label: 'J',
    tex: r'\text{J}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.20b9f9f5ca01',
    priority: 60,
    label: 'W',
    tex: r'\text{W}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.3d4ae2f17c86',
    priority: 60,
    label: 'Pa',
    tex: r'\text{Pa}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.07479cec8a84',
    priority: 60,
    label: 'Hz',
    tex: r'\text{Hz}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.611e91bf36ab',
    priority: 60,
    label: 'V',
    tex: r'\text{V}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.cb3cae87a33d',
    priority: 60,
    label: 'A',
    tex: r'\text{A}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.e67fca23b841',
    priority: 60,
    label: 'C',
    tex: r'\text{C}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.8cc1a6366d1c',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'F = ma',
    tex: r'F = ma',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.6828251b3e6c',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'p = mv',
    tex: r'p = mv',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.5533636f7520',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'v = u+at',
    tex: r'v = u + at',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.e6b3d24827d4',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 's = ut+½at²',
    tex: r's = ut + \frac{1}{2}at^2',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.62483fe43738',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'v² = u²+2as',
    tex: r'v^2 = u^2 + 2as',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.0defba1a0070',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'KE',
    tex: r'E_k = \frac{1}{2}mv^2',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.fec7b1d5dff3',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'PE',
    tex: r'E_p = mgh',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.27690e201fa4',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'P = W/t',
    tex: r'P = \frac{W}{t}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.347b075b0930',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'V = IR',
    tex: r'V = IR',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.051b31ed5240',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'P = VI',
    tex: r'P = VI',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.8710ef94a8e1',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'Q = It',
    tex: r'Q = It',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.011dddb16b4a',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'v = fλ',
    tex: r'v = f\lambda',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.518c60c1f875',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'ρ = m/V',
    tex: r'\rho = \frac{m}{V}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.c364af0054fb',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'P = F/A',
    tex: r'P = \frac{F}{A}',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.6beeeac940a0',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'Q = mcΔT',
    tex: r'Q = mc\Delta T',
    category: MathCategory.physics,
  ),
  MathSymbol(
    id: 'math.929c9c256745',
    kind: MathEntryKind.formulaTemplate,
    priority: 60,
    label: 'Lens',
    tex: r'\frac{1}{f}=\frac{1}{v}-\frac{1}{u}',
    category: MathCategory.physics,
  ),
];
