import '../models/math_edit_command.dart';
import '../models/math_symbol.dart';

/// Phase 5 expansion of high-value textbook and university notation.
///
/// Entries live in existing UI categories so this phase expands the semantic
/// universe without adding a new navigation category or changing persistence.
/// Renderer/parser compatibility remains a separate Phase 6 concern.
const List<MathSymbol> symbolUniverseExpansionMathSymbols = <MathSymbol>[
  MathSymbol(
    id: 'math.4c12e853b6bc',
    priority: 65,
    label: 'ι',
    tex: r'\iota',
    spokenLabel: 'iota',
    aliases: <String>['iota'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.397916aac987',
    priority: 65,
    label: 'κ',
    tex: r'\kappa',
    spokenLabel: 'kappa',
    aliases: <String>['kappa'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.697fbec64a12',
    priority: 65,
    label: 'ν',
    tex: r'\nu',
    spokenLabel: 'nu',
    aliases: <String>['nu'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.2bf5b3aa5637',
    priority: 65,
    label: 'ξ',
    tex: r'\xi',
    spokenLabel: 'xi',
    aliases: <String>['xi'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.ecaab5335bff',
    priority: 65,
    label: 'υ',
    tex: r'\upsilon',
    spokenLabel: 'upsilon',
    aliases: <String>['upsilon'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.e2ab8159ae04',
    priority: 65,
    label: 'χ',
    tex: r'\chi',
    spokenLabel: 'chi',
    aliases: <String>['chi'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.c774d4ea8480',
    priority: 65,
    label: 'ψ',
    tex: r'\psi',
    spokenLabel: 'psi',
    aliases: <String>['psi'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.abfcc7fffa77',
    priority: 65,
    label: 'ϵ',
    tex: r'\varepsilon',
    spokenLabel: 'variant epsilon',
    aliases: <String>['variant epsilon'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.dffd955c0128',
    priority: 65,
    label: 'ϑ',
    tex: r'\vartheta',
    spokenLabel: 'variant theta',
    aliases: <String>['variant theta'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.6ff7f2c95e23',
    priority: 65,
    label: 'ϖ',
    tex: r'\varpi',
    spokenLabel: 'variant pi',
    aliases: <String>['variant pi'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.2a60abc0b0c4',
    priority: 65,
    label: 'ϱ',
    tex: r'\varrho',
    spokenLabel: 'variant rho',
    aliases: <String>['variant rho'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.8a000332cf10',
    priority: 65,
    label: 'ς',
    tex: r'\varsigma',
    spokenLabel: 'final sigma',
    aliases: <String>['final sigma'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.44294dbd1964',
    priority: 65,
    label: 'ϕ',
    tex: r'\varphi',
    spokenLabel: 'variant phi',
    aliases: <String>['variant phi'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.d8c33e099eb0',
    priority: 65,
    label: 'Ξ',
    tex: r'\Xi',
    spokenLabel: 'capital xi',
    aliases: <String>['capital xi'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.2427b419df24',
    priority: 65,
    label: 'Υ',
    tex: r'\Upsilon',
    spokenLabel: 'capital upsilon',
    aliases: <String>['capital upsilon'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.2290bb0684c4',
    priority: 65,
    label: 'Ψ',
    tex: r'\Psi',
    spokenLabel: 'capital psi',
    aliases: <String>['capital psi'],
    category: MathCategory.greek,
  ),
  MathSymbol(
    id: 'math.22341972d49b',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '↦',
    tex: r'\mapsto',
    aliases: <String>['mapsto', 'maps to', 'function mapping'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.e8bcfe093afe',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '⟼',
    tex: r'\longmapsto',
    aliases: <String>['long mapsto', 'maps to'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.e55df23831c2',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '⟶',
    tex: r'\longrightarrow',
    aliases: <String>['long right arrow', 'long arrow'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.bf6a5f4a031f',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '⟵',
    tex: r'\longleftarrow',
    aliases: <String>['long left arrow'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.dedbc9c7110a',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '⇐',
    tex: r'\Leftarrow',
    aliases: <String>['left double arrow', 'implied by'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.660cd8398404',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '↪',
    tex: r'\hookrightarrow',
    aliases: <String>['hook right arrow', 'injection'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.2115b43cd2f9',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '↩',
    tex: r'\hookleftarrow',
    aliases: <String>['hook left arrow'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.ff8602397e71',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '↼',
    tex: r'\leftharpoonup',
    aliases: <String>['left harpoon', 'harpoon'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.0a77a1ca458a',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '⇀',
    tex: r'\rightharpoonup',
    aliases: <String>['right harpoon', 'harpoon'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.efafd9f316ef',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '⇋',
    tex: r'\leftrightharpoons',
    aliases: <String>['left right harpoons', 'reversible'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.8eb6ac08e4ee',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '⇌',
    tex: r'\rightleftharpoons',
    aliases: <String>[
      'right left harpoons',
      'equilibrium',
      'reversible reaction',
    ],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.c230f73fd261',
    kind: MathEntryKind.operator,
    priority: 66,
    label: '⇝',
    tex: r'\leadsto',
    aliases: <String>['leads to', 'leadsto'],
    category: MathCategory.arrows,
  ),
  MathSymbol(
    id: 'math.9204fd4be60a',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '·',
    tex: r'\cdot',
    aliases: <String>['dot multiply', 'center dot'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.algebra],
  ),
  MathSymbol(
    id: 'math.65cf20021222',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '∗',
    tex: r'\ast',
    aliases: <String>['asterisk operator', 'star operator'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.9312c2748cca',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⋆',
    tex: r'\star',
    aliases: <String>['star operator'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.9dd420e29092',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '•',
    tex: r'\bullet',
    aliases: <String>['bullet operator'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.c4b7092c0f7c',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⊕',
    tex: r'\oplus',
    aliases: <String>['direct sum', 'circled plus'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.linearAlgebra],
  ),
  MathSymbol(
    id: 'math.633322af137b',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⊖',
    tex: r'\ominus',
    aliases: <String>['circled minus'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.72166555a6db',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⊗',
    tex: r'\otimes',
    aliases: <String>['tensor product', 'circled times'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.linearAlgebra],
  ),
  MathSymbol(
    id: 'math.244f65495948',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⊘',
    tex: r'\oslash',
    aliases: <String>['circled slash'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.c8e2d1a0bf50',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⊙',
    tex: r'\odot',
    aliases: <String>['circled dot'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.4ce1dcdcb7e4',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⨁',
    tex: r'\bigoplus',
    aliases: <String>['big direct sum', 'direct sum'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.linearAlgebra],
  ),
  MathSymbol(
    id: 'math.f3c95cf8f1f8',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⨂',
    tex: r'\bigotimes',
    aliases: <String>['big tensor product', 'tensor product'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.linearAlgebra],
  ),
  MathSymbol(
    id: 'math.3435b1a63667',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⋁',
    tex: r'\bigvee',
    aliases: <String>['big logical or', 'big vee'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.logic],
  ),
  MathSymbol(
    id: 'math.84c8cd97bc48',
    kind: MathEntryKind.operator,
    priority: 67,
    label: '⋀',
    tex: r'\bigwedge',
    aliases: <String>['big logical and', 'big wedge'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.logic],
  ),
  MathSymbol(
    id: 'math.808f13f76e08',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '≃',
    tex: r'\simeq',
    aliases: <String>['similar or equal', 'simeq'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.84ef81af4d15',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '≍',
    tex: r'\asymp',
    aliases: <String>['asymptotically equal', 'asymp'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.7f38f3bed35e',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '≪',
    tex: r'\ll',
    aliases: <String>['much less than'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.343ac549460f',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '≫',
    tex: r'\gg',
    aliases: <String>['much greater than'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.68754fe0fef7',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '≺',
    tex: r'\prec',
    aliases: <String>['precedes', 'prec'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.be6332ab7ac9',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '≻',
    tex: r'\succ',
    aliases: <String>['succeeds', 'succ'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.a9a5ad657244',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '≼',
    tex: r'\preceq',
    aliases: <String>['precedes or equal'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.e8ea1ff5f75f',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '≽',
    tex: r'\succeq',
    aliases: <String>['succeeds or equal'],
    category: MathCategory.operators,
  ),
  MathSymbol(
    id: 'math.ddbf6923ea3f',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '∣',
    tex: r'\mid',
    aliases: <String>['divides', 'divisor relation', 'such that'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.numberTheory],
  ),
  MathSymbol(
    id: 'math.9e5b05507705',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '∤',
    tex: r'\nmid',
    aliases: <String>['does not divide', 'not divides'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.numberTheory],
  ),
  MathSymbol(
    id: 'math.657c200e047a',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '∄',
    tex: r'\nexists',
    aliases: <String>['there does not exist', 'not exists'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.logic],
  ),
  MathSymbol(
    id: 'math.2871a9b86384',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '⊤',
    tex: r'\top',
    aliases: <String>['truth', 'top element'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.logic],
  ),
  MathSymbol(
    id: 'math.9a3fe51ebc4d',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '⊥',
    tex: r'\bot',
    aliases: <String>['falsehood', 'bottom element'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.logic],
  ),
  MathSymbol(
    id: 'math.9108c923b5f8',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '⊢',
    tex: r'\vdash',
    aliases: <String>['proves', 'turnstile', 'syntactic entailment'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.logic],
  ),
  MathSymbol(
    id: 'math.5b08083b6076',
    kind: MathEntryKind.relation,
    priority: 68,
    label: '⊨',
    tex: r'\models',
    aliases: <String>['models', 'semantic entailment', 'satisfies'],
    category: MathCategory.operators,
    subjects: <MathSubject>[MathSubject.logic],
  ),
  MathSymbol(
    id: 'math.93536d5f95e8',
    kind: MathEntryKind.relation,
    priority: 69,
    label: '⊊',
    tex: r'\subsetneq',
    aliases: <String>['proper subset'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.90d1e47ff7af',
    kind: MathEntryKind.relation,
    priority: 69,
    label: '⊋',
    tex: r'\supsetneq',
    aliases: <String>['proper superset'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.4b75c4c6629b',
    kind: MathEntryKind.relation,
    priority: 69,
    label: '⊈',
    tex: r'\nsubseteq',
    aliases: <String>['not subset or equal', 'not subseteq'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.f54497d13a7d',
    kind: MathEntryKind.relation,
    priority: 69,
    label: '⊉',
    tex: r'\nsupseteq',
    aliases: <String>['not superset or equal', 'not supseteq'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.6e7622454af5',
    kind: MathEntryKind.operator,
    priority: 69,
    label: '∖',
    tex: r'\setminus',
    aliases: <String>['set difference', 'relative complement', 'minus set'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.604036ffddf4',
    kind: MathEntryKind.relation,
    priority: 69,
    label: '⊏',
    tex: r'\sqsubset',
    aliases: <String>['square subset'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.a72762414b8b',
    kind: MathEntryKind.relation,
    priority: 69,
    label: '⊑',
    tex: r'\sqsubseteq',
    aliases: <String>['square subset or equal'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.244c03ea093e',
    kind: MathEntryKind.relation,
    priority: 69,
    label: '⊐',
    tex: r'\sqsupset',
    aliases: <String>['square superset'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.8e889c1e20e0',
    kind: MathEntryKind.relation,
    priority: 69,
    label: '⊒',
    tex: r'\sqsupseteq',
    aliases: <String>['square superset or equal'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.003e6cf6d4db',
    kind: MathEntryKind.operator,
    priority: 69,
    label: '⊎',
    tex: r'\uplus',
    aliases: <String>['disjoint union', 'multiset union'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.13b4413340e5',
    kind: MathEntryKind.operator,
    priority: 69,
    label: '⊔',
    tex: r'\sqcup',
    aliases: <String>['square union', 'join'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.a352113c24f5',
    kind: MathEntryKind.operator,
    priority: 69,
    label: '⊓',
    tex: r'\sqcap',
    aliases: <String>['square intersection', 'meet'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.1f13a21ea4fe',
    kind: MathEntryKind.operator,
    priority: 69,
    label: '⋃',
    tex: r'\bigcup',
    aliases: <String>['big union', 'union over family'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.38ec0849b949',
    kind: MathEntryKind.operator,
    priority: 69,
    label: '⋂',
    tex: r'\bigcap',
    aliases: <String>['big intersection', 'intersection over family'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.7e3ceaecb9fa',
    kind: MathEntryKind.operator,
    priority: 69,
    label: '⨆',
    tex: r'\bigsqcup',
    aliases: <String>['big square union', 'big join'],
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.05dacc186289',
    kind: MathEntryKind.structure,
    priority: 58,
    label: '⋃ₐᵇ',
    tex: r'\bigcup_{}^{}',
    spokenLabel: 'big union with lower and upper limits',
    aliases: <String>['big union with limits', 'indexed union'],
    editorCommand: MathEditCommands.bigUnionWithLimits,
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.8e77603ca953',
    kind: MathEntryKind.structure,
    priority: 58,
    label: '⋂ₐᵇ',
    tex: r'\bigcap_{}^{}',
    spokenLabel: 'big intersection with lower and upper limits',
    aliases: <String>['big intersection with limits', 'indexed intersection'],
    editorCommand: MathEditCommands.bigIntersectionWithLimits,
    category: MathCategory.sets,
    subjects: <MathSubject>[MathSubject.sets],
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.c3765324db19',
    kind: MathEntryKind.structure,
    priority: 52,
    label: '(n r)',
    tex: r'\binom{}{}',
    spokenLabel: 'binomial coefficient',
    aliases: <String>[
      'binomial coefficient',
      'n choose r',
      'combination',
      'ncr',
    ],
    editorCommand: MathEditCommands.binomial,
    category: MathCategory.statistics,
    subjects: <MathSubject>[MathSubject.combinatorics, MathSubject.probability],
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.278e1e2e38e5',
    kind: MathEntryKind.structure,
    priority: 52,
    label: '(mod n)',
    tex: r'\pmod{}',
    spokenLabel: 'modulo argument',
    aliases: <String>['modulo', 'mod n', 'congruence modulus'],
    editorCommand: MathEditCommands.modulo,
    category: MathCategory.functions,
    subjects: <MathSubject>[MathSubject.numberTheory],
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.3f35bbc25861',
    kind: MathEntryKind.function,
    priority: 55,
    label: 'gcd',
    tex: r'\gcd',
    aliases: <String>[
      'greatest common divisor',
      'highest common factor',
      'hcf',
    ],
    editorCommand: MathEditCommands.gcdCall,
    category: MathCategory.functions,
    subjects: <MathSubject>[MathSubject.numberTheory],
  ),
  MathSymbol(
    id: 'math.0e7717ebda0b',
    kind: MathEntryKind.function,
    priority: 55,
    label: 'lcm',
    tex: r'\operatorname{lcm}',
    aliases: <String>['least common multiple', 'lowest common multiple'],
    editorCommand: MathEditCommands.lcmCall,
    category: MathCategory.functions,
    subjects: <MathSubject>[MathSubject.numberTheory],
  ),
  MathSymbol(
    id: 'math.ff886dca0180',
    kind: MathEntryKind.function,
    priority: 58,
    label: 'arg',
    tex: r'\arg',
    aliases: <String>[
      'complex argument',
      'argument of complex number',
      'phase',
    ],
    editorCommand: MathEditCommands.argCall,
    category: MathCategory.functions,
    subjects: <MathSubject>[MathSubject.complexNumbers],
  ),
  MathSymbol(
    id: 'math.fca85c689a1b',
    kind: MathEntryKind.function,
    priority: 58,
    label: 'Re',
    tex: r'\Re',
    aliases: <String>['real part', 'real component'],
    category: MathCategory.functions,
    subjects: <MathSubject>[MathSubject.complexNumbers],
  ),
  MathSymbol(
    id: 'math.78ccebf6b4ee',
    kind: MathEntryKind.function,
    priority: 58,
    label: 'Im',
    tex: r'\Im',
    aliases: <String>['imaginary part', 'imaginary component'],
    category: MathCategory.functions,
    subjects: <MathSubject>[MathSubject.complexNumbers],
  ),
  MathSymbol(
    id: 'math.f0d76e452a04',
    kind: MathEntryKind.structure,
    priority: 58,
    label: 'z̄',
    tex: r'\overline{}',
    spokenLabel: 'complex conjugate or overline',
    aliases: <String>['complex conjugate', 'conjugate', 'overline expression'],
    editorCommand: MathEditCommands.emptyOverline,
    category: MathCategory.functions,
    subjects: <MathSubject>[MathSubject.complexNumbers],
    isBuilder: true,
  ),
  MathSymbol(
    id: 'math.8e09d0a830d8',
    kind: MathEntryKind.constant,
    priority: 78,
    label: 'ℵ',
    tex: r'\aleph',
    aliases: <String>['aleph', 'cardinality', 'infinite cardinal'],
    category: MathCategory.misc,
    subjects: <MathSubject>[MathSubject.sets],
  ),
  MathSymbol(
    id: 'math.9aee3e478f33',
    kind: MathEntryKind.constant,
    priority: 70,
    label: 'ℏ',
    tex: r'\hbar',
    aliases: <String>['h bar', 'reduced planck constant'],
    category: MathCategory.physics,
    subjects: <MathSubject>[MathSubject.physics],
  ),
  MathSymbol(
    id: 'math.c7c068229f25',
    priority: 78,
    label: 'ℓ',
    tex: r'\ell',
    aliases: <String>['script ell', 'ell symbol'],
    category: MathCategory.misc,
  ),
  MathSymbol(
    id: 'math.7835130167f1',
    priority: 78,
    label: '⋯',
    tex: r'\cdots',
    aliases: <String>['center dots', 'horizontal dots', 'ellipsis'],
    category: MathCategory.misc,
  ),
  MathSymbol(
    id: 'math.00f1c80c6238',
    priority: 78,
    label: '⋮',
    tex: r'\vdots',
    aliases: <String>['vertical dots', 'vertical ellipsis'],
    category: MathCategory.misc,
  ),
  MathSymbol(
    id: 'math.ad27eb57c04b',
    priority: 78,
    label: '⋱',
    tex: r'\ddots',
    aliases: <String>['diagonal dots', 'diagonal ellipsis'],
    category: MathCategory.misc,
  ),
];
