import '../models/math_symbol.dart';

const List<MathSymbol> templatesMathSymbols = <MathSymbol>[
  MathSymbol(
      id: 'math.9325d49dfd08',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Quadratic',
      tex: r'x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.7815fae5f495',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Pythagoras',
      tex: r'a^2 + b^2 = c^2',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.43bce53bbbcf',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Circle',
      tex: r'(x-h)^2 + (y-k)^2 = r^2',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.27f3b706a514',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Line',
      tex: r'y = mx + c',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.64c71576caa1',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Slope',
      tex: r'm = \frac{y_2-y_1}{x_2-x_1}',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.713dedd916e0',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Distance',
      tex: r'd = \sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.8fcd4744071f',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'AP nth',
      tex: r'a_n = a + (n-1)d',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.7d4ac8048c12',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'AP Sum',
      tex: r'S_n = \frac{n}{2}[2a+(n-1)d]',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.6ed6b5268d0a',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'GP nth',
      tex: r'a_n = ar^{n-1}',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.7bffd0e1a6f7',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Mean',
      tex: r'\bar{x} = \frac{\sum x}{n}',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.4259c4b57f12',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Prob.',
      tex: r'P(E)=\frac{\text{Favourable outcomes}}{\text{Total outcomes}}',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.fe2d282df515',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Area circle',
      tex: r'A=\pi r^2',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.a5a3acc5ec07',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Volume sphere',
      tex: r'V=\frac{4}{3}\pi r^3',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.9d459bfcf1d2',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Solve',
      tex: r'\text{Solve: }',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.4e4e23739b8c',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Prove',
      tex: r'\text{Prove that }',
      category: MathCategory.templates,
    ),
  MathSymbol(
      id: 'math.b8a0b389cb47',
      kind: MathEntryKind.formulaTemplate,
      priority: 80,
      label: 'Find x',
      tex: r'\text{Find the value of } x',
      category: MathCategory.templates,
    ),
];
